### ISSUE TITLE
Unclear how to run plugin

### ISSUE THREAD

**Issue by oliviodare** [hipstersmoothie/obsidian-plugin-toc#1]
Hi, I am a bit unsure about how to actually run the plugin. This is a bit unclear from the README file. 

Having installed the plugin on Obsidian, opening the switcher as you show in the gif does not show a note for running the toc plugin. Something seems to be missing in the explanation

Thanks!

**Comment by hipstersmoothie** [comment]
Did you make sure to turn on the plugin after you installed it?

**Comment by oliviodare** [comment]
Yes, it's active.

**Comment by oliviodare** [comment]
Thanks, I saw the latest release with the updated README. Cheers!
