### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by dxcore35** [hipstersmoothie/obsidian-plugin-toc#2]
System: Mac OS big sur
Obsidian: 0.11.3

After pressing to create TOC in quick menu, nothing happens.

**Comment by hipstersmoothie** [comment]
The table of content is based on where your cursor is and the current heading in the file. Could you provide a sample price of content that isn't working?

**Comment by dxcore35** [comment]
1) The table of content is based on where your cursor = ?
- I tried to add cursor on beginning of the file
- I tried to add cursor to end of the file
> Nothing is inserted and nothing is in clipboard.

2) In note I'm using Heading on 1,2,3 level
3) I tried several of my notes with proper headings > Nothing is inserted and nothing is in clipboard.

**Comment by hipstersmoothie** [comment]
Okay I think I have addressed the issue with #5 and #6.

**Comment by dxcore35** [comment]
Very good no no issue. The TOC is generated perfectly!
I will not close the issue as you merged it with other issue, feel free to close if applicable.
