### ISSUE TITLE
Optional title is not inserted

### ISSUE THREAD

**Issue by DutchPete** [hipstersmoothie/obsidian-plugin-toc#3]
Thank you for a useful plug-in. The only minor issue I have encountered is that the plug-in does not insert the text `Table of Contents`.

**Comment by hipstersmoothie** [comment]
That's an option you have to configure in the plugins settings. Have you done that?

**Comment by DutchPete** [comment]
This what the optional setting looks like, which is the way it was already after installation:
![image](https://user-images.githubusercontent.com/10794265/109412763-8e17dc00-79b2-11eb-9690-913e5c468307.png)

What else do I need to do?

**Comment by hipstersmoothie** [comment]
That's the placeholder. You gave to fill it in

**Comment by DutchPete** [comment]
Ah, got it. Sorry, I thought that was a prefilled title, esp. since that is the text I want. Anyway, solved.
Thanks.
