### ISSUE TITLE
Numbering

### ISSUE THREAD

**Issue by DutchPete** [hipstersmoothie/obsidian-plugin-toc#7]
Instead of numbering like this:
1. text
2. text also
   1. subtext
   2. subtext also

do this:
1. text
2. text also
   2.1. subtext
   2.2. subtext also

**Comment by hipstersmoothie** [comment]
The only way to do this is to add a global css snippet for ordered lists https://github.com/hipstersmoothie/obsidian-plugin-toc#detailed-nested-ordered-lists

**Comment by DutchPete** [comment]
Thank you 👍
